//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheque
    {
        public Nullable<long> номер_чека { get; set; }
        public string наименование { get; set; }
        public int количество { get; set; }
        public Nullable<double> Скидка { get; set; }
        public Nullable<double> Цена { get; set; }
        public System.DateTime Дата { get; set; }
    }
}
