//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDZ_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public purchase()
        {
            this.purchase_item = new HashSet<purchase_item>();
        }
    
        public System.Guid purchase_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public System.Guid cashier_id { get; set; }
        public Nullable<System.Guid> discount_card_id { get; set; }
        public int cash_register_number { get; set; }
    
        public virtual cashiers cashiers { get; set; }
        public virtual discount_cards discount_cards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_item> purchase_item { get; set; }
    }
}
